update validator link
PufferFinance/website-docs pull request #22
Opened 2024-04-24 21:32 UTC by kamiyaa

2024-04-25 09:16 UTC, lean-apple commented on docs/setup.md
> +Example Output (assumes Docker image tag `1.0.0`, check for latest Docker image release [here](https://hub.docker.com/r/pufferfi/validator/tags)):
```suggestion
Example Output (assumes Docker image tag `1.1.0`, check for latest Docker image release [here](https://hub.docker.com/r/pufferfi/validator/tags)):
```

2024-04-25 09:16 UTC, lean-apple commented on docs/setup.md
> +docker.io/pufferfi/validator:1.0.0
```suggestion
docker.io/pufferfi/validator:1.1.0
```

2024-04-25 09:16 UTC, lean-apple commented on docs/setup.md
>  Status: Image is up to date for pufferfi/validator:1.0.0
```suggestion
Status: Image is up to date for pufferfi/validator:1.1.0
```

2024-04-25 09:16 UTC, lean-apple commented on docs/setup.md
> +Ensure image tag matches latest version described on testnet repository before running the next command! (Here image tag is 1.0.0)
```suggestion
Ensure image tag matches latest version described on testnet repository before running the next command! (Here image tag is 1.1.0)
```

2024-04-25 09:17 UTC, lean-apple requested changes
Thanks, but let's update the latest docker image tag also here to avoid custody failed and incompatible `MRENCLAVE`

2024-04-26 01:05 UTC, JasonVranek approved these changes

2024-04-26 01:05 UTC, merged